### PR TITLE
Add possibility to define custom region

### PR DESCRIPTION
**Pull request by maxilampert**

### CODE REVIEW

**Comment by mattmcspirit** [comment]
Hey, would you please change this PR to merge into branch 1901.1 instead of master? I need to make a few updates and will include this in the next release, if it passes my testing. I don’t think I can change the target merge branch but I think you can.

Thanks for the work!

**Comment by maxilampert** [comment]
Hi Matt, 

done 👍

**Comment by mattmcspirit** [comment]
The more i think about it, perhaps instead of doing $region, with a default value of "local", perhaps it's better to have $customARMendpoint, with a default of "local.azurestack.external"

I've had requests in the past for people following guides like this: https://blogs.blackmarble.co.uk/rhepworth/2018/09/22/deploying-the-asdk-for-effective-development-use/, and changing to a different external domain, such as west.contoso.local.

Would you be interested in changing your PR to include this instead of $region?

**Comment by maxilampert** [comment]
I wasn't sure in the first place if a change like that is desired in the ASDK configurator so I decided for the minimal invasive approach. But yes I think I have a good idea on how ti implement it. 

I would still keep the Region parameter but and rename it to RegionName add and a new paramter called externalDomainName which default is then "azurestack.external", that would give us the most flexibility in that case.

What do you think?

**Comment by mattmcspirit** [comment]
So here's the dilemma - i want to make sure it's as simple for me (selfishly!) as possible going forward, and adding one parameter (and the additional error checking/regex checking i'll need to write) would be optimal. Also, the reason i suggest just using the full $customARMendpoint, is because all of the other requests I've had from users, has been because they want to change the *whole* domain name, not just the region. In reality, if you're going to make the effort to change the region of the ASDK, you may as well customize it completely to make it more realistic.

When you deploy your ASDK, are you editing the DeploySingleNode.ps1 file, and just changing the region from "local" to something else?  You don't also modify the domain suffix in the same file?

For me, the simplest thing would be to have $customARMendpoint, or something like $customDomainSuffix and just set it to default "local.azurestack.external". For you, you would just change it to "yourRegion.azurestack.external".

**Comment by maxilampert** [comment]
okay, I use the InstallAzurestackPOC.ps1 and add the region and domainsuffix parameters to it, so I can run the rest normally (because the parameters get forwarded to the DeploySingleNode if they exist), I only needed the region to change (for multiple ASDKs and ADFS integration) but I rework it for the fill URL.

Will update the PR with a solution.

**Comment by mattmcspirit** [comment]
OK great, thanks!

**Comment by mattmcspirit** [comment]
Thank you for this work!

Before i merge this, this, did you recreate the .azpkg files for MSSQL and MySQL using the marketplace packaging tool?

Thanks!

**Comment by maxilampert** [comment]
Your welcome, probably will open another one to fix some other things :grinning:

Yes they are recreated with the marketplace tool.

**Comment by mattmcspirit** [comment]
Merged, thanks! Also, if you want to test against this version, just use -branch "1901.1" when you run the script.  Thanks!

**Comment by mattmcspirit** [comment]
One more thing we should add, is a validation that the custom domain suffix that the user enters, is a valid one. For instance, if i use -customDomainSuffix "%$231#.&5rtgfs.com", the script will initially progress, and eventually fail the first time it tries to reach the ARM Endpoint. We should use some kind of regex check to validate the data entry initially. I have some examples already present, but we should add one for this before we push this to the master branch.

**Comment by mattmcspirit** [comment]
Don't worry - I've done it :)

**Pull request merged**
